import React from "react";
import { MarketingLayout } from "../components/marketing/MarketingLayout.jsx";
import { T } from "../components/common/Theme.js";
function Page({ title, children }){
  React.useEffect(()=>{ document.title=`${title} — JobCompass`; },[title]);
  return <MarketingLayout><section style={{ maxWidth: 800, margin:"0 auto", padding:"40px 24px" }}><div style={{ fontSize:11, fontWeight:700, letterSpacing:"0.06em", color:T.hint }}>Last reviewed: August 2026</div><h1 style={{ fontSize:28, fontWeight:800, marginTop:6 }}>{title}</h1><div style={{ marginTop:16, fontSize:13, color:T.text, lineHeight:1.8 }}>{children}</div></section></MarketingLayout>;
}
export function Privacy(){ return <Page title="Privacy Policy"><p><b>Who we are:</b> Infonaut, the team behind JobCompass (jobcompass.io). <b>What we store:</b> your account details (name, email and the preferences you give us), the CV content you paste or build, the roles you save and apply to, and billing records created when you buy credits through Stripe. We never see or store your card details — payments are handled entirely by Stripe.</p><p><b>Where data lives:</b> all data is hosted on Cloudflare in UK/EU data centres. Your CVs and account records never leave that region.</p><p><b>Sign-in:</b> we use single-use 6-digit PIN codes sent to your email instead of passwords. Each code works once and expires in 10 minutes. Email is used only for sign-in codes and Stripe receipts.</p><p><b>No sale of data:</b> we do not sell, rent or trade your personal data with anyone. We use no advertising trackers.</p><p><b>Your rights:</b> you can access, correct, export or delete your data at any time by emailing support@jobcompass.io. See our full rights list under GDPR & Data Deletion.</p></Page>; }
export function Terms(){ return <Page title="Terms of Service"><p><b>Service:</b> JobCompass tailors your CV for UK roles. 1 credit = 1 application dossier: a tailored CV, a cover letter and screening-question answers. You get 5 free trial credits when you sign up — no card required.</p><p><b>Credits:</b> credits never expire. Buy them when you need them, use them whenever you like.</p><p><b>If a run fails:</b> if a tailoring run fails after a credit is deducted, you are refunded automatically — no need to ask.</p><p><b>No auto-submit:</b> JobCompass never submits applications for you. You review every tailored CV and apply yourself on the employer's site. We only mark the application as applied once you have done so.</p><p><b>Acceptable use:</b> don't misuse the service — no scraping, resale or attempting to trick the AI with embedded instructions in job descriptions. We may suspend accounts that abuse the service. JobCompass provides CV advice, not legal advice.</p><p><b>Governing law:</b> these terms are governed by the laws of England & Wales.</p></Page>; }
export function Cookies(){ return <Page title="Cookie Policy"><p><b>What we use:</b> exactly one thing — a session token stored in your browser's localStorage that keeps you signed in. It is not a tracking cookie and is never shared with third parties.</p><p><b>No third-party tracking cookies:</b> we run no analytics trackers, no advertising pixels and no social media cookies. Cloudflare may set a short-lived bot-protection cookie to keep the site safe.</p><p><b>Manage:</b> clear your browser's site data to sign out everywhere. Because we use essential storage only, no consent banner is needed — if that ever changes, you will see one.</p></Page>; }
export function Gdpr(){ return <Page title="GDPR & Data Deletion"><p><b>Your rights:</b> under UK/EU GDPR you have the right to access, rectification, erasure, restriction of processing, data portability and the right to object to processing.</p><p><b>Deleting your data:</b> you can delete any CV from within the app, or email support@jobcompass.io from your account address and ask us to delete everything. We complete deletion within 30 days and confirm by email.</p><p><b>Complaints:</b> you have the right to complain to the UK's supervisory authority, the Information Commissioner's Office (ICO), at any time — though we would appreciate the chance to fix things first.</p><p><b>Contact:</b> for any data request, email support@jobcompass.io. We respond within one month.</p></Page>; }
export function Refunds(){ return <Page title="Refunds & Credits"><p><b>Automatic refunds:</b> if a tailoring run is blocked or fails after a credit has been deducted, the credit is refunded to your balance automatically. You never lose a credit to a failed run.</p><p><b>Credits never expire:</b> unused credits stay on your account indefinitely. Buy in bulk, use slowly — they will be waiting.</p><p><b>Disputes:</b> if something looks wrong with a payment, raise it with Stripe directly or email support@jobcompass.io and we will trace the transaction and make it right.</p></Page>; }
export function About(){ return <Page title="About — Infonaut"><p><b>Who we are:</b> Infonaut builds UK-first job tools. We started JobCompass because US job-search tools get British CVs, salaries and compliance wrong — so we built one that doesn't.</p><p><b>How we build:</b> everything runs on Cloudflare, with your data kept in UK/EU data centres. Our AI drafts, a second AI audits, and you approve every change before anything is saved.</p><p><b>Contact:</b> support@jobcompass.io.</p></Page>; }
export function Contact(){ return <Page title="Contact"><p><b>Email:</b> support@jobcompass.io — we reply within 1–2 working days. Sign-in code not arriving? Check your spam folder for a message from noreply@jobcompass.io.</p><p><b>Billing questions:</b> include the email address on your account so we can find your payments and credit balance quickly.</p><p><b>Everything else:</b> browse open roles on the Jobs page, learn how tailoring works under How it works, or check the Status page if something seems off. No phone support yet — email only.</p></Page>; }
