import React from "react";
import { MarketingLayout } from "../components/marketing/MarketingLayout.jsx";
import { T } from "../components/common/Theme.js";
function Page({ title, children }){
  React.useEffect(()=>{ document.title=`${title} — JobCompass`; },[title]);
  return <MarketingLayout><section style={{ maxWidth: 800, margin:"0 auto", padding:"40px 24px" }}><div style={{ fontSize:11, fontWeight:700, letterSpacing:"0.06em", color:T.hint }}>Last reviewed: August 2026</div><h1 style={{ fontSize:28, fontWeight:800, marginTop:6 }}>{title}</h1><div style={{ marginTop:16, fontSize:13, color:T.text, lineHeight:1.8 }}>{children}</div></section></MarketingLayout>;
}
export function Privacy(){ return <Page title="Privacy Policy"><p><b>Who we are:</b> Infonaut, the team behind JobCompass (jobcompass.io). <b>What we keep:</b> your email, your CV, the jobs you save, and your payment record (handled by Stripe). We never sell your data.</p><p><b>Where it lives:</b> on Cloudflare's servers in the UK and EU. Your CV and account never leave that region.</p><p><b>Sign-in:</b> we email you a 6-digit code. It works once and expires in 10 minutes.</p><p><b>Email:</b> sign-in codes and Stripe receipts only. Nothing else.</p><p><b>No tracking:</b> we run no ads and no trackers. See our Cookie Policy.</p><p><b>Your rights:</b> ask us anytime to see, fix or delete your data — support@jobcompass.io. We delete within 30 days.</p><p><b>Complaints:</b> you can also complain to the ICO (the UK's data watchdog). We'd like the chance to fix things first, though.</p></Page>; }
export function Terms(){ return <Page title="Terms of Service"><p><b>What you get:</b> each job you tailor gives you a finished CV (one page, A4), a cover letter and answers to common application questions. Your first 10 jobs are free — no card needed.</p><p><b>Paying:</b> 10p per job. £10 gets you 100. They never expire.</p><p><b>If something breaks:</b> if a job fails after you're charged, we refund it automatically. You don't have to ask.</p><p><b>You're always in charge:</b> we never send applications for you. You look at every CV and press send yourself.</p><p><b>Playing fair:</b> don't misuse the service — no scraping, no resale, no trying to trick the helper with hidden instructions in job adverts. We can pause accounts that do.</p><p><b>Advice, not law:</b> JobCompass gives CV advice. It is not legal advice.</p><p><b>UK law applies</b> (England & Wales).</p></Page>; }
export function Cookies(){ return <Page title="Cookie Policy"><p><b>One thing:</b> we store a sign-in code in your browser so you stay logged in. No tracking, no ads, no third-party cookies.</p><p><b>Safety:</b> Cloudflare may set a short cookie to keep the site safe. That's all.</p><p><b>Want out:</b> clear your browser's site data and you're signed out everywhere. If this ever changes, you'll see a consent banner.</p></Page>; }
export function Gdpr(){ return <Page title="GDPR & Data Deletion"><p><b>Your rights:</b> ask to see, fix or delete your data anytime — support@jobcompass.io. We reply within one month and delete within 30 days.</p><p><b>Delete it yourself:</b> you can delete any CV inside the app. Or email us from your account address and we'll delete everything.</p><p><b>Complaints:</b> you can also complain to the ICO (the UK's data watchdog). Please tell us first if you can — we'd like to make it right.</p></Page>; }
export function Refunds(){ return <Page title="Refunds & Credits"><p><b>Failed jobs:</b> refunded automatically — you don't have to ask.</p><p><b>Credits never expire:</b> they stay on your account forever, so there's rarely anything to refund.</p><p><b>Paying by card:</b> Stripe's buyer protection applies too. Does something look wrong? Email support@jobcompass.io and we'll trace it.</p></Page>; }
export function About(){ return <Page title="About — Infonaut"><p><b>Who we are:</b> JobCompass is made by Infonaut, a small UK team on Cloudflare. We got tired of sending the same CV everywhere and getting nowhere.</p><p><b>The tool we wanted:</b> one that checks every word, never invents anything, and always asks before it sends. So we built it.</p><p><b>Say hello:</b> support@jobcompass.io.</p></Page>; }
export function Contact(){ return <Page title="Contact"><p><b>Email:</b> support@jobcompass.io. Tell us your sign-in email and we'll help within 2 working days.</p><p><b>Code not arriving:</b> check your spam folder for a message from noreply@jobcompass.io.</p><p><b>Billing:</b> include your sign-in email so we can find your payments fast.</p></Page>; }
