import React from "react";
import { MarketingLayout } from "../components/marketing/MarketingLayout.jsx";
import { T } from "../components/common/Theme.js";
function Page({ title, updated, children }){
  React.useEffect(()=>{ document.title=`${title} — JobCompass`; },[title]);
  return <MarketingLayout><section style={{ maxWidth: 800, margin:"0 auto", padding:"40px 24px" }}><div style={{ fontSize:11, fontWeight:700, letterSpacing:"0.06em", color:T.hint }}>UPDATED {updated}</div><h1 style={{ fontSize:28, fontWeight:800, marginTop:6 }}>{title}</h1><div style={{ marginTop:16, fontSize:13, color:T.text, lineHeight:1.8 }}>{children}</div></section></MarketingLayout>;
}
export function Privacy(){ return <Page title="Privacy Policy" updated="27 Aug 2026"><p><b>Controller:</b> Infonaut (jobcompass.io, support@jobcompass.io). <b>Where data lives:</b> D1 <code>jobcompass-db</code> (candidates, resumes, field_locks, constraints_docs, applications, credit_balances), R2 <code>jobcompass-pdfs</code>, KV <code>jobcompass-cache</code> (PIN hash TTL 600 only). All on Cloudflare, single region. No sale of data.</p><p><b>What we collect:</b> Email, full name, target role, location, salary band, phone, notice period, right-to-work, CV JSON + DID/DID NOT ground truth, applications + tailored PDFs. Email via <code>noreply@jobcompass.io</code> SPF/DKIM <code>email.ts:1</code> for PIN (6-digit SHA-256 <code>auth.ts:31</code>) + Stripe receipts only.</p><p><b>Legal basis:</b> Contract + consent + legitimate interest (security). <b>Retention:</b> Until you delete. <b>Rights:</b> Access/rectification/erasure/portability via support@jobcompass.io. <b>Cookies:</b> Only <code>agentic_cv_uk_token</code> JWT 24h <code>auth.ts:196</code> + local storage. See /cookies.</p><p><b>Transfers:</b> Cloudflare subprocessors only. <b>Contact:</b> support@jobcompass.io, 21-day response.</p></Page>; }
export function Terms(){ return <Page title="Terms of Service" updated="27 Aug 2026"><p><b>Service:</b> Agentic CV tailoring — 1 credit = 1 dossier (tailor DeepSeek V3 + verifier Claude Haiku + cover letter 300-340w + screening answers). 5 trial credits on signup <code>lib/credits.ts:9</code>. Credits never expire.</p><p><b>Payment:</b> Stripe GBP <code>billing.ts:62</code> packs Starter £10/100, Active £25/250, Power £50/500 (£0.10/app). Receipt via Email Sending. Idempotent on <code>reference_id</code> unique <code>schema.sql:111</code>. Overpay? Contact support.</p><p><b>Refund:</b> Auto refund if tailor fails post-deduct <code>routes/resumes.ts:102</code>. Otherwise non-refundable except statutory. No auto-apply — you submit via <code>sourceUrl</code> + <code>PUT /applications/:id status applied</code>.</p><p><b>Acceptable use:</b> No injection (JD treated as passive data <code>tailor.ts:27</code>), no scraping, no resale. We may suspend abuse. British CV advice, not legal advice. Governing law: England & Wales.</p></Page>; }
export function Cookies(){ return <Page title="Cookie Policy" updated="27 Aug 2026"><p><b>Essential only:</b> <code>agentic_cv_uk_token</code> (HS256 JWT 24h) in localStorage, plus <code>CACHE</code> KV rate limit. No analytics/marketing cookie without consent. Cloudflare may set <code>__cf_bm</code> for bot protection.</p><p><b>Manage:</b> Clear site data in browser. No consent banner needed for essential-only. If we add analytics later, banner will appear.</p></Page>; }
export function Gdpr(){ return <Page title="GDPR & Data Deletion" updated="27 Aug 2026"><p><b>Your rights:</b> Access, rectification, erasure, restriction, portability, objection. <b>Delete:</b> <code>DELETE /resumes/:id</code> hard-deletes D1 row, or email support@jobcompass.io with email + candidateId. We delete within 30 days, confirm by email.</p><p><b>Re:</b> Rejected &gt;90d may be archived then purged. PDFs in R2 deleted with resume. No photo/DOB/NI stored unless you provide them — verifier blocks <code>fieldRegistry.js:70</code>. DPA available on request. Supervisory authority: ICO (UK).</p></Page>; }
export function Refunds(){ return <Page title="Refunds & Credits" updated="27 Aug 2026"><p><b>Snapshot:</b> Credits non-refundable except <b>auto-refund</b> when tailor blocks or throws after deduct — <code>addCredits(refund)</code> <code>lib/credits.ts:9</code> with idempotent <code>reference_id</code> <code>billing.ts:154</code>. Stripe webhooks are idempotent so retries never double-credit.</p><p><b>Disputes:</b> Raise via Stripe or support@jobcompass.io with <code>session.id</code>. We check <code>credit_transactions where reference_id=session.id</code>. Credits never expire vs subscription trap (Teal $9/w, Huntr ~$40/mo).</p></Page>; }
export function About(){ return <Page title="About — Infonaut" updated="27 Aug 2026"><p><b>Mission:</b> UK job search, done properly — agentic tailoring you can trust, not volume you regret. Built Cloudflare-native (D1/R2/KV/Queue/Vectorize/Workers AI/Email) — no Postgres, no vendor lock.</p><p><b>How:</b> 12-stage pipeline <code>AGENT_FLOW.md:1</code> — registry → tailor (DeepSeek) → validate → quickVerify → patched → verifier (Haiku) → corrective → persist → matcher → HITL → PDF A4 → apply. Every edit is JSON Patch over registry; raw LLM never touches D1.</p><p><b>Who:</b> Infonaut — jobcompass.io. Contact support@jobcompass.io. Tagline built to beat $1M ARR US tools on UK specificity.</p></Page>; }
export function Contact(){ return <Page title="Contact" updated="27 Aug 2026"><p><b>Email:</b> support@jobcompass.io (replies 1–2 days). For <b>PIN issues</b> search spam for <code>noreply@jobcompass.io</code> <code>email.ts:11</code>. For <b>billing</b> include <code>candidateId</code> + Stripe <code>session.id</code>.</p><p><b>Addresses:</b> Jobs: <code>GET /jobs/library</code> public, companies: <code>GET /companies</code> public, health: <code>GET /health</code>. No phone support yet — email only. We log <code>ingest_runs</code> per provider for debug.</p></Page>; }
